# Generated by Django 5.2.13 on 2026-05-09 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_question_java_constraints_question_java_customized_and_more'),
        ('submissions', '0002_questiondraft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questiondraft',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='questiondraft',
            name='language',
            field=models.CharField(default='python', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='questiondraft',
            unique_together={('user', 'question', 'language')},
        ),
    ]
