# Generated by Django 6.0.4 on 2026-05-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_add_kicked_at_to_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='enable_security_features',
            field=models.BooleanField(default=True, help_text='If enabled, participants will be logged out for exiting fullscreen or switching tabs.'),
        ),
    ]
