# Generated by Django 6.0.4 on 2026-05-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_contest_enable_security_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='manual_control_mode',
            field=models.BooleanField(default=False, help_text='If enabled, timers are disabled and sections must be manually unlocked by the admin.'),
        ),
        migrations.AddField(
            model_name='section',
            name='is_manual_unlocked',
            field=models.BooleanField(default=False, help_text='Only used if Contest is in Manual Control Mode.'),
        ),
    ]
