# Generated by Django 6.0.4 on 2026-05-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_contest_manual_control_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testcase_images/'),
        ),
    ]
