# Generated by Django 6.0.4 on 2026-05-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_contestparticipant_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipant',
            name='kicked_at',
            field=models.DateTimeField(blank=True, help_text='Set when participant exits/is kicked. Blocks normal login until cleared by rejoin.', null=True),
        ),
    ]
