# Generated by Django 5.2.13 on 2026-05-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_testcase_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipant',
            name='compile_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of Compile & Run attempts'),
        ),
        migrations.AddField(
            model_name='contestparticipant',
            name='submit_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of Submit Code attempts'),
        ),
    ]
