# Generated by Django 5.2.13 on 2026-05-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_contestparticipant_compile_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='java_constraints',
            field=models.TextField(blank=True, help_text='Java-specific constraints'),
        ),
        migrations.AddField(
            model_name='question',
            name='java_customized',
            field=models.BooleanField(default=False, help_text='If enabled, Java participants see custom problem text below instead of the default Python text.'),
        ),
        migrations.AddField(
            model_name='question',
            name='java_input_format',
            field=models.TextField(blank=True, help_text='Java-specific input format'),
        ),
        migrations.AddField(
            model_name='question',
            name='java_output_format',
            field=models.TextField(blank=True, help_text='Java-specific output format'),
        ),
        migrations.AddField(
            model_name='question',
            name='java_problem_statement',
            field=models.TextField(blank=True, help_text='Java-specific problem statement (used only if Java Customized is checked)'),
        ),
        migrations.AddField(
            model_name='question',
            name='java_sample_input',
            field=models.TextField(blank=True, help_text='Java-specific sample input'),
        ),
        migrations.AddField(
            model_name='question',
            name='java_sample_output',
            field=models.TextField(blank=True, help_text='Java-specific sample output'),
        ),
    ]
