version = 5.5.0
archive_dir = /etc/letsencrypt/archive/battlecodearena.gispilibhit.com
cert = /etc/letsencrypt/live/battlecodearena.gispilibhit.com/cert.pem
privkey = /etc/letsencrypt/live/battlecodearena.gispilibhit.com/privkey.pem
chain = /etc/letsencrypt/live/battlecodearena.gispilibhit.com/chain.pem
fullchain = /etc/letsencrypt/live/battlecodearena.gispilibhit.com/fullchain.pem
[renewalparams]
account = 9e5a831407be9584951b580a6e15a8f8
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
[acme_renewal_info]
ari_retry_after = 2026-05-07T17:48:31
